### ISSUE TITLE
🐛 Bug Report: Creating an index with index type key fails. Then the error toast is unreadable.

### ISSUE THREAD

**Issue by xpediteur** [appwrite/console#1429]
### 👟 Reproduction steps

When i create an index with index type "key, " an error toast appears, but the toast is blurred ( not readable)![Image](https://github.com/user-attachments/assets/798648b5-f57f-4856-874f-398cb0faeaed)

### 👍 Expected behavior

Error toast should be readable.

### 👎 Actual Behavior

Toast is blurred. It could be a UI problem.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

MacOS

### 🧱 Your Environment

new Version of SDK.

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Instead of showing a notification, we should be setting the error like we do for the create attribute modal:

https://github.com/appwrite/console/blob/b3ac06b27dd62708950352d8da51596afee0e177/src/routes/(console)/project-%5Bproject%5D/databases/database-%5Bdatabase%5D/collection-%5Bcollection%5D/createAttribute.svelte#L79

**Comment by xpediteur** [comment]
perhaps a css z-index problem

**Comment by ItzNotABug** [comment]
Should be fixed via - https://github.com/appwrite/console/pull/1538.
